/**
 * Icon names from @meysam213/iconsax-react (1020 icons).
 * Variants are appended to the name when looking up exports: Sax{Name}{Variant}
 */
export const ICONSAX_VARIANTS = ['Linear', 'Outline', 'Broken', 'Bold', 'Bulk', 'TwoTone'] as const
export type IconsaxVariant = typeof ICONSAX_VARIANTS[number]

export const ICONSAX_ICON_NAMES: string[] = [
  '24Support', '3DCubeScan', '3DRotate', '3DSquare', '3Dcube', '3Square',
  'Activity', 'Add', 'AddCircle', 'AddSquare', 'Additem', 'Airdrop', 'Airplane', 'AirplaneSquare',
  'Airpod', 'Airpods', 'Alarm', 'AlignBottom', 'AlignHorizontally', 'AlignLeft', 'AlignRight', 'AlignVertically',
  'Aquarius', 'Archive', 'Archive1', 'ArchiveAdd', 'ArchiveBook', 'ArchiveMinus', 'ArchiveSlash', 'ArchiveTick',
  'ArrangeCircle', 'ArrangeCircle2', 'ArrangeSquare', 'ArrangeSquare2',
  'Arrow', 'Arrow2', 'Arrow3', 'ArrowBottom', 'ArrowCircleDown', 'ArrowCircleLeft', 'ArrowCircleRight',
  'ArrowDown', 'ArrowDown1', 'ArrowDown2', 'ArrowLeft', 'ArrowLeft1', 'ArrowLeft2', 'ArrowLeft3',
  'ArrowRight', 'ArrowRight1', 'ArrowRight2', 'ArrowRight3',
  'ArrowSquare', 'ArrowSquareDown', 'ArrowSquareLeft', 'ArrowSquareRight', 'ArrowSquareUp',
  'ArrowSwapHorizontal', 'ArrowUp', 'ArrowUp1', 'ArrowUp2', 'ArrowUp3',
  'AttachCircle', 'AttachSquare', 'AudioSquare', 'Autobrightness', 'Award',
  'BackSquare', 'Backward', 'Backward10Seconds', 'Backward15Seconds', 'Backward5Seconds',
  'BackwardItem', 'BackwardItem1',
  'Bag', 'Bag2', 'BagCross', 'BagCross1', 'BagHappy', 'BagTick', 'BagTick2', 'BagTimer',
  'Bank', 'Barcode', 'Battery3Full', 'BatteryCharging', 'BatteryDisable', 'BatteryEmpty', 'BatteryEmpty1', 'BatteryFull',
  'Bezier', 'Bezier1', 'Bill', 'BitcoinCard', 'BitcoinConvert', 'BitcoinRefresh',
  'Blend', 'Blend2', 'Bluetooth', 'Bluetooth2', 'BluetoothCircle', 'BluetoothRectangle', 'Blur', 'Blur1',
  'Book', 'Book1', 'BookSaved', 'BookSquare', 'Bookmark', 'Bookmark2',
  'Box', 'Box1', 'Box2', 'BoxAdd', 'BoxRemove', 'BoxSearch', 'BoxTick', 'BoxTime',
  'Briefcase', 'BrifecaseCross', 'BrifecaseTick', 'BrifecaseTimer',
  'Broom', 'Brush', 'Brush1', 'Brush2', 'Brush3', 'Bubble',
  'BucketCircle', 'BucketCircle1', 'BucketSquare', 'BucketSquare1',
  'Building', 'Building3', 'Building4', 'Buildings', 'Buildings2', 'Buliding', 'Bus', 'BuyCrypto',
  'Cake', 'Calculator', 'Calendar', 'Calendar1', 'Calendar2', 'CalendarAdd', 'CalendarCircle',
  'CalendarEdit', 'CalendarRemove', 'CalendarSearch', 'CalendarTick',
  'Call', 'CallAdd', 'CallCalling', 'CallIncoming', 'CallMinus', 'CallOutgoing', 'CallReceived', 'CallRemove', 'CallSlash',
  'Camera', 'CameraSlash', 'Candle', 'Candle2', 'Car',
  'Card', 'CardAdd', 'CardCoin', 'CardEdit', 'CardPos', 'CardReceive', 'CardRemove', 'CardRemove1',
  'CardSend', 'CardSlash', 'CardTick', 'CardTick1', 'Cards',
  'Category', 'Category2', 'Cd',
  'Chart', 'Chart1', 'Chart2', 'Chart21', 'Chart3', 'ChartSquare', 'ChartSuccess',
  'Check', 'Chrome', 'Clipboard', 'ClipboardClose', 'ClipboardExport', 'ClipboardImport', 'ClipboardText', 'ClipboardTick',
  'Clock', 'Clock1', 'CloseCircle', 'CloseSquare',
  'Cloud', 'CloudAdd', 'CloudChange', 'CloudConnection', 'CloudCross', 'CloudDrizzle', 'CloudFog',
  'CloudLightning', 'CloudMinus', 'CloudNotif', 'CloudPlus', 'CloudRemove', 'CloudSnow', 'CloudSunny',
  'Code', 'Code1', 'CodeCircle', 'Coffee', 'Coin', 'Coin1',
  'ColorSwatch', 'Colorfilter', 'ColorsSquare', 'ColorsSquare1',
  'Command', 'CommandSquare', 'Component', 'Component1', 'Computing',
  'Convert', 'Convert3DCube', 'Convertshape', 'Convertshape2',
  'Copy', 'CopySuccess', 'Copyright', 'Courthouse', 'Cpu', 'CpuCharge', 'CpuSetting', 'CreativeCommons',
  'Crop', 'Crown', 'Crown1', 'Cup',
  'Danger', 'Data', 'Data2', 'Designtools', 'DeviceMessage', 'Devices', 'Devices1', 'Diagram', 'Diamonds',
  'Direct', 'DirectDown', 'DirectInbox', 'DirectLeft', 'DirectNormal', 'DirectNotification',
  'DirectRight', 'DirectSend', 'DirectUp',
  'DirectboxDefault', 'DirectboxNotif', 'DirectboxReceive', 'DirectboxSend',
  'DiscountCircle', 'DiscountShape', 'Discover', 'Discover1', 'Dislike',
  'Document', 'Document1', 'DocumentCloud', 'DocumentCode', 'DocumentCode2', 'DocumentCopy',
  'DocumentDownload', 'DocumentFavorite', 'DocumentFilter', 'DocumentForward', 'DocumentLike',
  'DocumentNormal', 'DocumentPrevious', 'DocumentSketch', 'DocumentText', 'DocumentText1', 'DocumentUpload',
  'DollarCircle', 'DollarSquare', 'Driver', 'Driver2', 'DriverRefresh', 'Driving', 'Drop',
  'Edit', 'Edit2', 'Electricity',
  'Element1', 'Element2', 'Element3', 'Element4', 'ElementEqual', 'ElementPlus',
  'EmojiHappy', 'EmojiNormal', 'EmojiSad',
  'EmptyWallet', 'EmptyWalletAdd', 'EmptyWalletChange', 'EmptyWalletRemove', 'EmptyWalletTick', 'EmptyWalletTime',
  'Eraser', 'Eraser1', 'Eraser2',
  'Export', 'Export1', 'Export2', 'Export3', 'ExternalDrive', 'Eye', 'EyeSlash',
  'Fatrows', 'FavoriteChart',
  'Filter', 'FilterAdd', 'FilterEdit', 'FilterRemove', 'FilterSearch', 'FilterSquare', 'FilterTick',
  'FingerCricle', 'FingerScan', 'Firstline', 'Flag', 'Flag2',
  'Flash', 'Flash1', 'FlashCircle', 'FlashCircle1', 'FlashCircle2', 'FlashSlash',
  'Folder', 'Folder2', 'FolderAdd', 'FolderCloud', 'FolderConnection', 'FolderCross', 'FolderFavorite', 'FolderMinus', 'FolderOpen',
  'FormatCircle', 'FormatSquare',
  'Forward', 'Forward10Seconds', 'Forward15Seconds', 'Forward5Seconds', 'ForwardItem', 'ForwardItem1', 'ForwardSquare',
  'Frame', 'Frame1', 'Frame2', 'Frame3', 'Frame4', 'Frame5',
  'Gallery', 'GalleryAdd', 'GalleryEdit', 'GalleryExport', 'GalleryFavorite', 'GalleryImport',
  'GalleryRemove', 'GallerySlash', 'GalleryTick',
  'Game', 'Gameboy', 'GasStation', 'Gemini', 'Gemini2', 'Ghost', 'Gift', 'Glass', 'Glass1',
  'Global', 'GlobalEdit', 'GlobalRefresh', 'GlobalSearch',
  'Gps', 'GpsSlash', 'Grammerly', 'Graph',
  'Grid1', 'Grid2', 'Grid3', 'Grid4', 'Grid5', 'Grid6', 'Grid7', 'Grid8', 'Grid9',
  'GridEdit', 'GridEraser', 'GridLock',
  'Group', 'Group1', 'Group2', 'Group3', 'Group4', 'Group5', 'Group6', 'Group7', 'Group8', 'Group9', 'Group10', 'Group11',
  'Happyemoji', 'Hashtag', 'Hashtag1', 'HashtagDown', 'HashtagUp',
  'Headphone', 'Headphones', 'Health',
  'Heart', 'HeartAdd', 'HeartCircle', 'HeartEdit', 'HeartRemove', 'HeartSearch', 'HeartSlash', 'HeartTick',
  'Hierarchy', 'Hierarchy2', 'Hierarchy3', 'HierarchySquare', 'HierarchySquare2', 'HierarchySquare3',
  'Home', 'Home2', 'HomeHashtag', 'HomeTrendDown', 'HomeTrendUp', 'HomeWifi',
  'Hospital', 'House', 'House2',
  'Image', 'Import', 'Import1', 'Import2', 'InfoCircle', 'Information', 'Instagram',
  'Judge', 'Kanban', 'Key', 'KeySquare', 'Keyboard', 'KeyboardOpen',
  'Lamp', 'Lamp1', 'LampCharge', 'LampOn', 'LampSlash', 'LanguageCircle', 'LanguageSquare',
  'Layer', 'Level', 'Lifebuoy',
  'Like', 'Like1', 'LikeDislike', 'LikeShapes', 'LikeTag',
  'Link', 'Link1', 'Link2', 'Link21', 'LinkCircle', 'LinkSquare',
  'Location', 'LocationAdd', 'LocationCross', 'LocationMinus', 'LocationSlash', 'LocationTick',
  'Lock', 'Lock1', 'LockCircle', 'LockSlash', 'Login', 'Login1', 'Logout', 'Logout1', 'Lovely',
  'MagicStar', 'Magicpen', 'MainComponent', 'MainComponent1', 'Man', 'Map', 'Map1',
  'Mask', 'Mask1', 'Mask2', 'Mask3', 'Math',
  'Maximize', 'Maximize1', 'Maximize2', 'Maximize21', 'Maximize3', 'Maximize4', 'MaximizeCircle',
  'Medal', 'MedalStar', 'Menu', 'Menu1', 'MenuBoard',
  'Message', 'Message2', 'MessageAdd', 'MessageAdd1', 'MessageCircle', 'MessageEdit', 'MessageFavorite',
  'MessageMinus', 'MessageNotif', 'MessageProgramming', 'MessageQuestion', 'MessageRemove',
  'MessageSearch', 'MessageSquare', 'MessageText', 'MessageText1', 'MessageTick', 'MessageTime',
  'Messages', 'Messages1', 'Messages2', 'Messages3',
  'Microphone', 'Microphone2', 'MicrophoneSlash', 'MicrophoneSlash1', 'Microscope', 'Milk',
  'MiniMusicSqaure', 'Minus', 'MinusCirlce', 'MinusSquare', 'Mirror', 'MirroringScreen',
  'Mobile', 'MobileProgramming',
  'Money', 'Money2', 'Money3', 'Money4', 'MoneyAdd', 'MoneyChange', 'MoneyForbidden',
  'MoneyRecive', 'MoneyRemove', 'MoneySend', 'MoneyTick', 'MoneyTime', 'Moneys',
  'Monitor', 'MonitorMobbile', 'MonitorRecorder', 'Moon',
  'More', 'More2', 'MoreCircle', 'MoreSquare',
  'Mouse', 'Mouse1', 'MouseCircle', 'MouseSquare',
  'Music', 'MusicCircle', 'MusicDashboard', 'MusicFilter', 'MusicLibrary2', 'MusicPlay',
  'MusicPlaylist', 'MusicSquare', 'MusicSquareAdd', 'MusicSquareRemove', 'MusicSquareSearch', 'Musicnote',
  'Next', 'Note', 'Note1', 'Note2', 'Note21', 'NoteAdd', 'NoteFavorite', 'NoteRemove', 'NoteSquare', 'NoteText',
  'Notification', 'Notification1', 'NotificationBing', 'NotificationCircle', 'NotificationFavorite', 'NotificationStatus',
  'OmegaCircle', 'OmegaCircle1', 'OmegaSquare', 'OmegaSquare1',
  'Paintbucket', 'Paperclip', 'Paperclip2', 'PasswordCheck',
  'Path', 'Path2', 'PathSquare',
  'Pause', 'PauseCircle',
  'PenAdd', 'PenAdd1', 'PenClose', 'PenClose1', 'PenRemove', 'PenRemove1',
  'PenTool', 'PenTool1', 'PenTool2', 'PenTool21',
  'People', 'PercentageSquare', 'Personalcard', 'Pet', 'Pharagraphspacing', 'PictureFrame',
  'Play', 'PlayAdd', 'PlayCircle', 'PlayCricle', 'PlayRemove',
  'PresentionChart', 'Previous', 'Printer', 'PrinterSlash',
  'Profile', 'Profile2User', 'ProfileAdd', 'ProfileCircle', 'ProfileDelete', 'ProfileRemove', 'ProfileTick',
  'ProgrammingArrow', 'ProgrammingArrows',
  'QuoteDown', 'QuoteDownCircle', 'QuoteDownSquare', 'QuoteUp', 'QuoteUpCircle', 'QuoteUpSquare',
  'Radar', 'Radar1', 'Radar2', 'Radio', 'Ram', 'Ram2', 'Ranking', 'Ranking1',
  'Receipt', 'Receipt1', 'Receipt2', 'Receipt21', 'ReceiptAdd', 'ReceiptDiscount', 'ReceiptDisscount',
  'ReceiptEdit', 'ReceiptItem', 'ReceiptMinus', 'ReceiptSearch', 'ReceiptSquare', 'ReceiptText',
  'ReceiveSquare', 'ReceiveSquare2', 'Received', 'Record', 'RecordCircle', 'RecoveryConvert',
  'Redo', 'Refresh', 'Refresh2', 'RefreshCircle', 'RefreshLeftSquare', 'RefreshRightSquare', 'RefreshSquare2',
  'Repeat', 'RepeatCircle', 'RepeateMusic', 'RepeateOne', 'Reserve',
  'RotateLeft', 'RotateLeft1', 'RotateRight', 'RotateRight1',
  'RouteSquare', 'Routing', 'Routing2', 'RowHorizontal', 'RowVertical', 'Ruler', 'Rulerpen',
  'SafeHome', 'Sagittarius', 'Save2', 'SaveAdd', 'SaveMinus', 'SaveRemove',
  'Scan', 'ScanBarcode', 'Scanner', 'Scanning', 'Scissor', 'Scissor1', 'Scissor2', 'Screenmirroring', 'Scroll',
  'SearchFavorite', 'SearchFavorite1', 'SearchNormal', 'SearchNormal1',
  'SearchStatus', 'SearchStatus1', 'SearchZoomIn', 'SearchZoomIn1', 'SearchZoomOut', 'SearchZoomOut1',
  'Security', 'SecurityCard', 'SecuritySafe', 'SecurityTime', 'SecurityUser',
  'Send', 'Send1', 'Send2', 'SendSqaure2', 'SendSquare',
  'Setting', 'Setting2', 'Setting3', 'Setting4', 'Setting5', 'Settings',
  'Shapes', 'Shapes1', 'Shapes2', 'Share',
  'Shield', 'ShieldCross', 'ShieldSearch', 'ShieldSecurity', 'ShieldSlash', 'ShieldTick',
  'Ship', 'Shop', 'ShopAdd', 'ShopRemove', 'ShoppingBag', 'ShoppingCart',
  'SidebarBottom', 'SidebarLeft', 'SidebarRight', 'SidebarTop', 'Signpost',
  'Simcard', 'Simcard1', 'Simcard2', 'Size', 'Slash',
  'Slider', 'SliderHorizontal', 'SliderHorizontal1', 'SliderVertical', 'SliderVertical1',
  'Smallcaps', 'SmartCar', 'SmartHome', 'Smileys',
  'Sms', 'SmsEdit', 'SmsNotification', 'SmsSearch', 'SmsStar', 'SmsTracking',
  'Sort', 'Sound', 'Speaker', 'Speedometer',
  'Star', 'Star1', 'StarSlash', 'Status', 'StatusUp',
  'Sticker', 'Stickynote', 'Stop', 'StopCircle', 'Story', 'Strongbox', 'Strongbox2', 'Subtitle',
  'Sun', 'Sun1', 'SunFog',
  'Tag', 'Tag2', 'TagCross', 'TagRight', 'TagUser',
  'Task', 'TaskSquare', 'Teacher',
  'Text', 'TextBlock', 'TextBold', 'TextItalic', 'TextUnderline',
  'TextalignCenter', 'TextalignJustifycenter', 'TextalignJustifyleft', 'TextalignJustifyright', 'TextalignLeft', 'TextalignRight',
  'TickCircle', 'TickSquare',
  'Ticket', 'Ticket2', 'TicketDiscount', 'TicketExpired', 'TicketStar',
  'Timer', 'Timer1', 'TimerPause', 'TimerStart',
  'ToggleOff', 'ToggleOffCircle', 'ToggleOn', 'ToggleOnCircle',
  'Trade', 'TransactionMinus', 'Translate', 'Trash', 'Tree', 'TrendDown', 'TrendUp', 'Triangle',
  'TruckRemove', 'TruckTick', 'TruckTime', 'TrushSquare',
  'Undo', 'Unlimited', 'Unlock',
  'User', 'UserAdd', 'UserCirlceAdd', 'UserEdit', 'UserMinus', 'UserOctagon',
  'UserRemove', 'UserSearch', 'UserSquare', 'UserTag', 'UserTick',
  'Verify', 'Video', 'VideoAdd', 'VideoCircle', 'VideoHorizontal', 'VideoOctagon', 'VideoPlay',
  'VideoRemove', 'VideoSlash', 'VideoSquare', 'VideoTick', 'VideoTime', 'VideoVertical',
  'VoiceCricle', 'VoiceSquare',
  'VolumeCross', 'VolumeHigh', 'VolumeLow', 'VolumeLow1', 'VolumeMute', 'VolumeSlash', 'VolumeUp',
  'Wallet', 'Wallet1', 'Wallet2', 'Wallet3', 'WalletAdd', 'WalletAdd1', 'WalletCheck',
  'WalletMinus', 'WalletMoney', 'WalletRemove', 'WalletSearch',
  'Warning2', 'Watch', 'WatchStatus', 'Weight', 'Weight1',
  'Wifi', 'WifiSquare', 'Wind', 'Wind2', 'Woman',
]
